source 'https://rubygems.org'

gem 'activerecord-sqlserver-adapter', '~> 6.0.0'
gem 'dotenv-rails', '~> 2.7'
gem 'friendly_id', '~> 5.4'
gem 'haml-rails', '~> 2.0'
gem 'puma', '~> 5.1'
gem 'rails', '~> 6.0.3'
gem 'tiny_tds', '~> 2.1'
gem 'webpacker', '~> 5.2'
